//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARKETPLACE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public string id_producto { get; set; }
        public int idmarca { get; set; }
        public int idcategoria { get; set; }
        public string nombre_producto { get; set; }
        public byte[] img_producto { get; set; }
        public decimal preciof_producto { get; set; }
        public string desc_producto { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual marca marca { get; set; }
    }
}
