//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARKETPLACE.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RocketMarkets2Entities : DbContext
    {
        public RocketMarkets2Entities()
            : base("name=RocketMarkets2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<afiliado> afiliado { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<distrito> distrito { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<sexo> sexo { get; set; }
        public virtual DbSet<tipo_empresa> tipo_empresa { get; set; }
        public virtual DbSet<tipo_permiso> tipo_permiso { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
