//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARKETPLACE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos
    {
        public string id { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public string cod_tiper { get; set; }
    
        public virtual tipo_permiso tipo_permiso { get; set; }
    }
}
