//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARKETPLACE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int id_producto { get; set; }
        public Nullable<int> idcategoria { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> fechaCreado { get; set; }
        public Nullable<System.DateTime> fecaModificado { get; set; }
        public string nombre_producto { get; set; }
        public string img_producto { get; set; }
        public decimal preciof_producto { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public string desc_producto { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual categoria categoria { get; set; }
    }
}
