//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARKETPLACE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int idpais { get; set; }
        public string usuario { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual pais pais { get; set; }
    }
}
