//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARKETPLACE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int codigo { get; set; }
        public string nombres { get; set; }
        public Nullable<int> idpais { get; set; }
        public Nullable<int> idsexo { get; set; }
        public string email { get; set; }
        public string contraseña { get; set; }
        public string confir_contraseña { get; set; }
    
        public virtual pais pais { get; set; }
        public virtual sexo sexo { get; set; }
    }
}
